# Generated by Django 4.0.1 on 2022-05-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
